- name: Install Nginx
  hosts: webservers
  become: true
  
  tasks:
    - name: Install Nginx (Fedora/RHEL/CentOS)
      yum:
        name: nginx
        state: present
        update_cache: yes
      notify: Restart nginx
      when: ansible_os_family == "RedHat"
      tags:
        - installation

    - name: Install Nginx Debian
      apt:
        name: nginx{{ nginx_version | default('') }}
        state: present
        update_cache: yes
      notify: Restart nginx
      when: ansible_os_family == "Debian"
      tags:
        - installation

    - name: CONFIGURE NGINX TO START AT BOOT
      block:
        - name: backup old config
          copy:
            src: /etc/nginx/nginx.conf
            dest: /etc/nginx/nginx.conf.bak
            remote_src: yes
        - name: deploy new config
          template:
            src: etc/nginx/nginx.conf.j2
            dest: /etc/nginx/nginx.conf
          notify: Restart nginx

        - name: Create a directory
          become: true
          ansible.builtin.file:
            path: /etc/nginx/sites-enabled/
            state: directory
            mode: '0755'
        - name: copy default.j2 config to sites-enabled
          become: true
          template:
            src: etc/nginx/sites-enabled/default.j2
            dest: /etc/nginx/sites-enabled/default
          notify: Restart nginx

        - name: Create a directory for deploy
          become: true
          ansible.builtin.file:
            path: /var/www/html
            state: directory
            mode: '0755'
      rescue:
        - name: Restore old config
          copy:
            src: /etc/nginx/nginx.conf.bak
            dest: /etc/nginx/nginx.conf
            remote_src: yes
          notify: Restart nginx

    - name: deploy an html file
      copy:
        dest: "/var/www/html/index.html"
        content: "<h1>Hello sur le serveur Nginx déployé par Ansible !</h1>"
      notify: Restart nginx
      tags:
        - deployment

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

    - name: Creer un repertoire de déploiment
      file:
        dest: "{{ deploy_path }}"
        owner: "{{ user }}"
        mode: '0755'
        state: directory

